package MScheme.values.functions;

/* --- DON'T EDIT --- */
/* this file is generated by MScheme.values.functions.ParseBuiltins */

import MScheme.util.Arity;

import MScheme.Value;
import MScheme.Code;

import MScheme.values.*;
import MScheme.machine.Registers;

import MScheme.exceptions.*;


class BuiltinRaw
    extends    Function
    implements BuiltinTable
{
    public final static String id
        = "$Id$";


    private final int    _id;
    private final String _name;

    BuiltinRaw(int id, String name)
    { _id = id; _name = name; }

    public String getName() { return _name; }

    public Function getFunc() { return this; }

    protected Value checkedCall(List args)
        throws SchemeException
    {
        switch(_id) {
        case 1: // list
            return Builtins.list(args);

        case 15: // <
            return Builtins._3C(args);

        case 16: // <=
            return Builtins._3C_3D(args);

        case 17: // =
            return Builtins._3D(args);

        case 18: // >=
            return Builtins._3E_3D(args);

        case 19: // >
            return Builtins._3E(args);

        case 21: // +
            return Builtins._2B(args);

        case 22: // -
            return Builtins._2D(args);

        case 23: // *
            return Builtins._2A(args);

        case 52: // string-append
            return Builtins.string_2Dappend(args);

        case 61: // vector
            return Builtins.vector(args);

        default:
            throw new RuntimeException("unexpected Id");
        }
    }

    protected Arity getArity()
    { return Arity.atLeast(0); }

    public Code call(Registers state, List args)
        throws SchemeException
    { return checkedCall(args).getLiteral(); }
}

class BuiltinThunks
    extends    ValueThunk
    implements BuiltinTable
{
    public final static String id
        = "$Id$";


    private final int    _id;
    private final String _name;

    BuiltinThunks(int id, String name)
    { _id = id; _name = name; }

    public String getName() { return _name; }

    public Function getFunc() { return this; }

    protected Value checkedCall()
        throws SchemeException
    {
        switch(_id) {
        default:
            throw new RuntimeException("unexpected Id");
        }
    }
}

class BuiltinUnary
    extends    UnaryValueFunction
    implements BuiltinTable
{
    public final static String id
        = "$Id$";


    private final int    _id;
    private final String _name;

    BuiltinUnary(int id, String name)
    { _id = id; _name = name; }

    public String getName() { return _name; }

    public Function getFunc() { return this; }

    protected Value checkedCall(Value fst)
        throws SchemeException
    {
        switch(_id) {
        case 0: // length
            return Builtins.length(fst);

        case 3: // reverse
            return Builtins.reverse(fst);

        case 4: // read
            return Builtins.read(fst);

        case 8: // number?
            return Builtins.number_3F(fst);

        case 9: // complex?
            return Builtins.complex_3F(fst);

        case 10: // real?
            return Builtins.real_3F(fst);

        case 11: // rational?
            return Builtins.rational_3F(fst);

        case 12: // integer?
            return Builtins.integer_3F(fst);

        case 13: // exact?
            return Builtins.exact_3F(fst);

        case 14: // inexact?
            return Builtins.inexact_3F(fst);

        case 20: // zero?
            return Builtins.zero_3F(fst);

        case 24: // not
            return Builtins.not(fst);

        case 25: // boolean?
            return Builtins.boolean_3F(fst);

        case 26: // pair?
            return Builtins.pair_3F(fst);

        case 28: // car
            return Builtins.car(fst);

        case 29: // cdr
            return Builtins.cdr(fst);

        case 32: // null?
            return Builtins.null_3F(fst);

        case 33: // list?
            return Builtins.list_3F(fst);

        case 34: // symbol?
            return Builtins.symbol_3F(fst);

        case 35: // symbol->string
            return Builtins.symbol_2D_3Estring(fst);

        case 36: // string->symbol
            return Builtins.string_2D_3Esymbol(fst);

        case 37: // char?
            return Builtins.char_3F(fst);

        case 43: // char->integer
            return Builtins.char_2D_3Einteger(fst);

        case 44: // integer->char
            return Builtins.integer_2D_3Echar(fst);

        case 45: // char-upcase
            return Builtins.char_2Dupcase(fst);

        case 46: // char-downcase
            return Builtins.char_2Ddowncase(fst);

        case 47: // string?
            return Builtins.string_3F(fst);

        case 49: // string-length
            return Builtins.string_2Dlength(fst);

        case 53: // string-copy
            return Builtins.string_2Dcopy(fst);

        case 54: // string->list
            return Builtins.string_2D_3Elist(fst);

        case 55: // list->string
            return Builtins.list_2D_3Estring(fst);

        case 56: // vector?
            return Builtins.vector_3F(fst);

        case 58: // vector-length
            return Builtins.vector_2Dlength(fst);

        case 62: // vector->list
            return Builtins.vector_2D_3Elist(fst);

        case 63: // list->vector
            return Builtins.list_2D_3Evector(fst);

        case 64: // procedure?
            return Builtins.procedure_3F(fst);

        case 65: // scheme-report-environment
            return Builtins.scheme_2Dreport_2Denvironment(fst);

        case 66: // null-environment
            return Builtins.null_2Denvironment(fst);

        case 67: // port?
            return Builtins.port_3F(fst);

        case 68: // input-port?
            return Builtins.input_2Dport_3F(fst);

        case 69: // output-port?
            return Builtins.output_2Dport_3F(fst);

        case 70: // open-input-file
            return Builtins.open_2Dinput_2Dfile(fst);

        case 71: // open-output-file
            return Builtins.open_2Doutput_2Dfile(fst);

        case 72: // close-input-port
            return Builtins.close_2Dinput_2Dport(fst);

        case 73: // close-output-port
            return Builtins.close_2Doutput_2Dport(fst);

        case 74: // read-char
            return Builtins.read_2Dchar(fst);

        case 75: // peek-char
            return Builtins.peek_2Dchar(fst);

        case 76: // eof-object?
            return Builtins.eof_2Dobject_3F(fst);

        case 77: // char-ready?
            return Builtins.char_2Dready_3F(fst);

        default:
            throw new RuntimeException("unexpected Id");
        }
    }
}

class BuiltinBinary
    extends    BinaryValueFunction
    implements BuiltinTable
{
    public final static String id
        = "$Id$";


    private final int    _id;
    private final String _name;

    BuiltinBinary(int id, String name)
    { _id = id; _name = name; }

    public String getName() { return _name; }

    public Function getFunc() { return this; }

    protected Value checkedCall(Value fst, Value snd)
        throws SchemeException
    {
        switch(_id) {
        case 2: // write
            return Builtins.write(fst, snd);

        case 5: // eq?
            return Builtins.eq_3F(fst, snd);

        case 6: // eqv?
            return Builtins.eqv_3F(fst, snd);

        case 7: // equal?
            return Builtins.equal_3F(fst, snd);

        case 27: // cons
            return Builtins.cons(fst, snd);

        case 30: // set-car!
            return Builtins.set_2Dcar_21(fst, snd);

        case 31: // set-cdr!
            return Builtins.set_2Dcdr_21(fst, snd);

        case 38: // char<?
            return Builtins.char_3C_3F(fst, snd);

        case 39: // char<=?
            return Builtins.char_3C_3D_3F(fst, snd);

        case 40: // char=?
            return Builtins.char_3D_3F(fst, snd);

        case 41: // char>=?
            return Builtins.char_3E_3D_3F(fst, snd);

        case 42: // char>?
            return Builtins.char_3E_3F(fst, snd);

        case 48: // make-string
            return Builtins.make_2Dstring(fst, snd);

        case 50: // string-ref
            return Builtins.string_2Dref(fst, snd);

        case 57: // make-vector
            return Builtins.make_2Dvector(fst, snd);

        case 59: // vector-ref
            return Builtins.vector_2Dref(fst, snd);

        case 78: // display
            return Builtins.display(fst, snd);

        case 79: // write-char
            return Builtins.write_2Dchar(fst, snd);

        default:
            throw new RuntimeException("unexpected Id");
        }
    }
}

class BuiltinTernary
    extends    TernaryValueFunction
    implements BuiltinTable
{
    public final static String id
        = "$Id$";


    private final int    _id;
    private final String _name;

    BuiltinTernary(int id, String name)
    { _id = id; _name = name; }

    public String getName() { return _name; }

    public Function getFunc() { return this; }

    protected Value checkedCall(Value fst, Value snd, Value trd)
        throws SchemeException
    {
        switch(_id) {
        case 51: // string-set!
            return Builtins.string_2Dset_21(fst, snd, trd);

        case 60: // vector-set!
            return Builtins.vector_2Dset_21(fst, snd, trd);

        default:
            throw new RuntimeException("unexpected Id");
        }
    }
}

class BuiltinTableEntry
    implements BuiltinTable
{
    public final static String id
        = "$Id$";

    private final Function _func;
    private final String   _name;

    BuiltinTableEntry(Function func, String name)
    { _func = func; _name = name; }

    public String getName() { return _name; }

    public Function getFunc() { return _func; }
}


public interface BuiltinTable
{
    String id
        = "$Id$";


    String getName();
    Function getFunc();

    BuiltinTable[] builtins = {
        new BuiltinTableEntry(Builtins.append, "append"),
        new BuiltinTableEntry(Builtins.memq, "memq"),
        new BuiltinTableEntry(Builtins.memv, "memv"),
        new BuiltinTableEntry(Builtins.member, "member"),
        new BuiltinTableEntry(Builtins.assq, "assq"),
        new BuiltinTableEntry(Builtins.assv, "assv"),
        new BuiltinTableEntry(Builtins.assoc, "assoc"),
        new BuiltinTableEntry(Builtins.apply, "apply"),
        new BuiltinTableEntry(Builtins.call_2Dwith_2Dcurrent_2Dcontinuation, "call-with-current-continuation"),
        new BuiltinTableEntry(Builtins.dynamic_2Dwind, "dynamic-wind"),
        new BuiltinTableEntry(Builtins.eval, "eval"),
        new BuiltinUnary(0, "length"),
        new BuiltinRaw(1, "list"),
        new BuiltinBinary(2, "write"),
        new BuiltinUnary(3, "reverse"),
        new BuiltinUnary(4, "read"),
        new BuiltinBinary(5, "eq?"),
        new BuiltinBinary(6, "eqv?"),
        new BuiltinBinary(7, "equal?"),
        new BuiltinUnary(8, "number?"),
        new BuiltinUnary(9, "complex?"),
        new BuiltinUnary(10, "real?"),
        new BuiltinUnary(11, "rational?"),
        new BuiltinUnary(12, "integer?"),
        new BuiltinUnary(13, "exact?"),
        new BuiltinUnary(14, "inexact?"),
        new BuiltinRaw(15, "<"),
        new BuiltinRaw(16, "<="),
        new BuiltinRaw(17, "="),
        new BuiltinRaw(18, ">="),
        new BuiltinRaw(19, ">"),
        new BuiltinUnary(20, "zero?"),
        new BuiltinRaw(21, "+"),
        new BuiltinRaw(22, "-"),
        new BuiltinRaw(23, "*"),
        new BuiltinUnary(24, "not"),
        new BuiltinUnary(25, "boolean?"),
        new BuiltinUnary(26, "pair?"),
        new BuiltinBinary(27, "cons"),
        new BuiltinUnary(28, "car"),
        new BuiltinUnary(29, "cdr"),
        new BuiltinBinary(30, "set-car!"),
        new BuiltinBinary(31, "set-cdr!"),
        new BuiltinUnary(32, "null?"),
        new BuiltinUnary(33, "list?"),
        new BuiltinUnary(34, "symbol?"),
        new BuiltinUnary(35, "symbol->string"),
        new BuiltinUnary(36, "string->symbol"),
        new BuiltinUnary(37, "char?"),
        new BuiltinBinary(38, "char<?"),
        new BuiltinBinary(39, "char<=?"),
        new BuiltinBinary(40, "char=?"),
        new BuiltinBinary(41, "char>=?"),
        new BuiltinBinary(42, "char>?"),
        new BuiltinUnary(43, "char->integer"),
        new BuiltinUnary(44, "integer->char"),
        new BuiltinUnary(45, "char-upcase"),
        new BuiltinUnary(46, "char-downcase"),
        new BuiltinUnary(47, "string?"),
        new BuiltinBinary(48, "make-string"),
        new BuiltinUnary(49, "string-length"),
        new BuiltinBinary(50, "string-ref"),
        new BuiltinTernary(51, "string-set!"),
        new BuiltinRaw(52, "string-append"),
        new BuiltinUnary(53, "string-copy"),
        new BuiltinUnary(54, "string->list"),
        new BuiltinUnary(55, "list->string"),
        new BuiltinUnary(56, "vector?"),
        new BuiltinBinary(57, "make-vector"),
        new BuiltinUnary(58, "vector-length"),
        new BuiltinBinary(59, "vector-ref"),
        new BuiltinTernary(60, "vector-set!"),
        new BuiltinRaw(61, "vector"),
        new BuiltinUnary(62, "vector->list"),
        new BuiltinUnary(63, "list->vector"),
        new BuiltinUnary(64, "procedure?"),
        new BuiltinUnary(65, "scheme-report-environment"),
        new BuiltinUnary(66, "null-environment"),
        new BuiltinUnary(67, "port?"),
        new BuiltinUnary(68, "input-port?"),
        new BuiltinUnary(69, "output-port?"),
        new BuiltinUnary(70, "open-input-file"),
        new BuiltinUnary(71, "open-output-file"),
        new BuiltinUnary(72, "close-input-port"),
        new BuiltinUnary(73, "close-output-port"),
        new BuiltinUnary(74, "read-char"),
        new BuiltinUnary(75, "peek-char"),
        new BuiltinUnary(76, "eof-object?"),
        new BuiltinUnary(77, "char-ready?"),
        new BuiltinBinary(78, "display"),
        new BuiltinBinary(79, "write-char"),
    };
}